In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
data = pd.read_excel('Dataset commercial.xlsx')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date_premier_contact  20 non-null     datetime64[ns]
 1   Commercial            20 non-null     object
 2   Commercial_ID         0 non-null      float64
 3   Prospect_Nom          0 non-null      float64
 4   Type Client           1 non-null      object
 5   Secteur_Acvité        0 non-null      float64
 6   Produit               20 non-null     object
 7   Statut                20 non-null     object
 8   Date_conversion       20 non-null     datetime64[ns]
 9   Montant_souscription  20 non-null     int64
 10  Souscription_esperé   0 non-null      float64
 11  Mail                  0 non-null      float64
 12  Contact               0 non-null      float64
dtypes: datetime64[ns](2), float64(6), int64(1), object(4)
memory usage: 2.2+ KB

KeyError: "None of [Index(['N'GUESSAN GRACE ROMANCE', 'KOUASSI NELLY', 'MONNEY IMAMIAH'], dtype='object')] are in the [columns]"

In [8]:
Grace = data[data['Commercial'] == "N'GUESSAN GRACE ROMANCE"]

In [9]:
Grace

,Date_premier_contact,Commercial,Commercial_ID,Prospect_Nom,Type Client,Produit,Statut,Date_conversion,Montant_souscription,Canal,Notes
0,2025-06-02,N'GUESSAN GRACE ROMANCE,NaN,KADIO Y BOSSON,Particuliers,United Capital Diamond,Converti,2025-09-01,500000,NaN,NaN
1,2025-06-02,N'GUESSAN GRACE ROMANCE,NaN,KADIO Y BOSSON,NaN,United Capital Sapphire,Converti,2025-11-11,400000,NaN,NaN
2,2025-06-23,N'GUESSAN GRACE ROMANCE,NaN,GNAHOUA Didier,NaN,United Capital Diamond,Converti,2025-08-18,6500000,NaN,NaN
3,2025-06-23,N'GUESSAN GRACE ROMANCE,NaN,GNAHOUA Didier,NaN,United Capital Sapphire,Converti,2025-08-18,3500000,NaN,NaN
15,2025-11-13,N'GUESSAN GRACE ROMANCE,NaN,Stephane FONKOUA,NaN,United Capital Diamond,Converti,2025-12-10,13000000,NaN,NaN
16,2025-12-02,N'GUESSAN GRACE ROMANCE,NaN,DIALLO Maimouna Peinda,NaN,United Capital Sapphire,Converti,2025-12-19,10000000,NaN,NaN
17,2025-12-02,N'GUESSAN GRACE ROMANCE,NaN,DIALLO Maimouna Peinda,NaN,United Capital Diamond,Converti,2025-12-31,20000000,NaN,NaN

In [18]:
data['Date_premier_contact'] = pd.to_datetime(data['Date_premier_contact'])
data['Date_conversion'] = pd.to_datetime(data['Date_conversion'])

In [23]:
# Date de référence = aujourd’hui
date_ref = pd.Timestamp.today()

# Fenêtre 3 mois glissants
date_3_mois = date_ref - pd.DateOffset(months=3)

df_3_mois = data[
    (data['Statut'] == 'Converti') &
    (data['Date_conversion'] >= date_3_mois)
]

In [32]:
df_3_mois

,Date_premier_contact,Commercial,Commercial_ID,Prospect_Nom,Type Client,Produit,Statut,Date_conversion,Montant_souscription,Canal,Notes
1,2025-06-02,N'GUESSAN GRACE ROMANCE,NaN,KADIO Y BOSSON,NaN,United Capital Sapphire,Converti,2025-11-11,400000,NaN,NaN
13,2025-10-28,KOUASSI NELLY,NaN,BROU EHUI (Groupe IFSM),NaN,United Capital Sapphire,Converti,2025-11-24,203300,NaN,NaN
14,2025-11-12,KOUASSI NELLY,NaN,DUA Cyrille,NaN,United Capital Sapphire,Converti,2025-11-17,6101000,NaN,NaN
15,2025-11-13,N'GUESSAN GRACE ROMANCE,NaN,Stephane FONKOUA,NaN,United Capital Diamond,Converti,2025-12-10,13000000,NaN,NaN
16,2025-12-02,N'GUESSAN GRACE ROMANCE,NaN,DIALLO Maimouna Peinda,NaN,United Capital Sapphire,Converti,2025-12-19,10000000,NaN,NaN
17,2025-12-02,N'GUESSAN GRACE ROMANCE,NaN,DIALLO Maimouna Peinda,NaN,United Capital Diamond,Converti,2025-12-31,20000000,NaN,NaN
18,2025-12-06,KOUASSI NELLY,NaN,COULIBALY Myriam,NaN,United Capital Diamond,Converti,2025-11-24,12000000,NaN,NaN
19,2025-12-18,MONNEY IMAMIAH,NaN,BLEDOU Anne-Marie,NaN,United Capital Diamond,Converti,2025-12-23,1000000,NaN,NaN

In [ ]:
#Nombre de nouveaux clients sur les 3 derniers mois
Newclient = df_3_mois[df_3_mois['Statut'] == 'Converti']['Prospect_Nom'].shape[0]

In [35]:
Newclient

8

In [37]:
df_3_grace = df_3_mois[df_3_mois['Commercial'] == "N'GUESSAN GRACE ROMANCE"]

In [38]:
df_3_grace[df_3_grace['Statut'] == 'Converti']['Prospect_Nom'].shape[0]

4

In [49]:
#Taux de conversion global

taux_conversion = (
    data[data['Statut'] == 'Converti'].shape[0] /
    data.shape[0]
)

print(f"Taux de conversion : {taux_conversion:.2%}")

Taux de conversion : 100.00%

In [51]:
#Délai médian de conversion
df_conversion = data[data['Statut'] == 'Converti'].copy()

df_conversion['Delai_conversion'] = (
    df_conversion['Date_conversion'] - df_conversion['Date_premier_contact']
).dt.days

delai_median = df_conversion['Delai_conversion'].median()

print(f"Délai médian de conversion : {delai_median} jours")

Délai médian de conversion : 27.0 jours

In [52]:
#Montant souscrit total

montant_total = (
    data[data['Statut'] == 'Converti']['Montant_souscription']
    .sum()
)

print(f"Montant souscrit total : {montant_total:,.0f}")

Montant souscrit total : 151,231,300

In [53]:
pipeline_actif = data[data['Statut'] != 'Converti']

nb_pipeline = pipeline_actif['Prospect_Nom'].nunique()

print(f"Pipeline actif non converti : {nb_pipeline} prospects")

Pipeline actif non converti : 0 prospects

In [55]:
pipeline_actif['Age_pipeline'] = (
    pd.Timestamp.today() - pipeline_actif['Date_premier_contact']
).dt.days

pipeline_ancien = pipeline_actif[pipeline_actif['Age_pipeline'] > 150]

print(f"Pipeline dormant (>30j) : {pipeline_ancien.shape[0]} prospects")

Pipeline dormant (>30j) : 0 prospects

In [11]:
Nbre_client = Grace[Grace['Statut'] == 'Converti']['Prospect_Nom'].shape[0]
Nbre_client

7

In [12]:
Montant_total = Grace['Montant_souscription'].sum()
Montant_total

np.int64(53900000)