In [1]:
import pandas as pd
from KPI import nb_campagnes_marketing, engagement_digital, nb_followers_campagnes, performance_volume_partenariats,taux_transformation_partenariat,nb_partenariats_conclus,nb_partenariats_inities

In [2]:
donné = pd.read_excel('Imamiah Monney.xlsx', sheet_name=None)
clé = list(donné.keys())
Partenariat_df = donné[clé[0]]
Campagne_df = donné[clé[1]]

In [18]:
Partenariat_df

,nom_partenaire,type_partenaire,commercial_responsable,date_premier_contact,statut,origine_contact,objectif_volume,volume_realise
0,NaN,NaN,Imamiah Monney,NaN,abandonné,Prospection,5000000.0,150000.0
1,,Entreprise,Imamiah Monney,NaN,Signé,Referral,NaN,NaN
2,NaN,Banque,Imamiah Monney,NaN,abandonné,Prospection,NaN,NaN
3,NaN,autre,Imamiah Monney,NaN,NaN,NaN,NaN,NaN

In [4]:
Campagne_df

,campaign_id,nom_campagne,type_campagne,canal,date_lancement,date_fin,budget,impressions,likes,comments,shares,followers_avant,followers_apres
0,NaN,NaN,terrain,LinkedIn,2026-01-14,2026-03-05,5000000,520,50000,1000,50,500,100.0
1,NaN,NaN,institutionnelle,Email,2026-01-15,2026-03-06,5000000,520,50000,1000,50,500,NaN
2,NaN,NaN,digitale,Email,2026-01-16,2026-03-07,5000000,520,50000,1000,50,500,NaN
3,NaN,NaN,institutionnelle,Email,2026-01-17,2026-03-08,5000000,520,50000,1000,50,500,NaN
4,NaN,NaN,terrain,Autre,2026-01-18,2026-03-09,5000000,520,50000,1000,50,500,NaN
5,NaN,NaN,terrain,NaN,2026-01-19,2026-03-10,5000000,520,50000,1000,50,500,NaN

In [ ]:
partenariats_initie = nb_partenariats_inities(Partenariat_df)
Partenariat_conclu = nb_partenariats_conclus(Partenariat_df)
taux_transformation_partenaria =taux_transformation_partenariat(Partenariat_df)
performance_volume_partenariats = performance_volume_partenariats(Partenariat_df)
nb_campagnes_marketing = nb_campagnes_marketing(Campagne_df)
engagement_digital = engagement_digital(Campagne_df)
nb_followers_campagnes = nb_followers_campagnes(Campagne_df)

TypeError: 'float' object is not callable

In [22]:
Partenariat_conclus/partenariats_inities

ZeroDivisionError: division by zero

In [6]:
Partenariat

0

In [7]:
Partenariat_conclus

1

In [14]:
taux_transformation_partenariat = taux_transformation_partenariat(Partenariat_df)

TypeError: 'float' object is not callable

In [8]:
taux_transformation_partenariat

0.0

In [9]:
performance_volume_partenariats

{'objectif_total': 5000000.0,
 'realise_total': 150000.0,
 'taux_realisation': 0.03,
 'detail_par_partenaire': {'        ': {'objectif_volume': 0.0,
   'volume_realise': 0.0}}}

In [10]:
nb_campagnes_marketing

0

In [11]:
engagement_digital

{'total_impressions': 3120,
 'total_likes': 300000,
 'total_comments': 6000,
 'total_shares': 300,
 'taux_engagement': np.float64(98.1731),
 'nb_campagnes': 0,
 'budget_total': 30000000.0}

In [12]:
nb_followers_campagnes

{'total_nouveaux_followers': -400,
 'detail_par_canal': {'Autre': 0, 'Email': 0, 'LinkedIn': -400}}